# Generated by Django 4.2.1 on 2023-05-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.RemoveField(
            model_name='roomrate',
            name='rate',
        ),
    ]
