# Generated by Django 4.2.1 on 2023-05-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_price_remove_roomrate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.IntegerField(max_length=50),
        ),
    ]
