# Generated by Django 4.2.1 on 2023-05-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_roomrate_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomrate',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='price',
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='RoomRate',
        ),
    ]
