# Generated by Django 4.2.1 on 2023-06-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_remove_roomrate_room_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
