# Generated by Django 4.2.1 on 2023-05-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('amenities', models.TextField(default='NONE', max_length=140)),
                ('hotel_image', models.ImageField(upload_to='media/hotel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
