# Generated by Django 4.2.1 on 2023-06-01 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0002_hotel_hotel_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Hotel_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_hoteladmin', to=settings.AUTH_USER_MODEL),
        ),
    ]
