# Generated by Django 4.2.1 on 2023-06-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_hotel_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
