# Generated by Django 4.2.1 on 2023-06-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteluser',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
